FROM python:3.7.9

RUN mkdir -p /fetch
RUN mkdir -p /init
RUN mkdir -p /simulation-tools

# copy the source code files to the container
COPY fetch/ /fetch/
COPY init/ /init/
COPY simulation-tools/ /simulation-tools/

# install the python libraries
RUN pip install -r /fetch/requirements.txt

WORKDIR /

CMD [ "python", "-u", "-m", "fetch.fetch" ]
