version: '3.5'

services:

    fetch:
        build:
            context: .
            dockerfile: Dockerfile-fetch
        image: fetch:0.1
        container_name: FetchManifests
        restart: "no"
        env_file:
            - access_tokens.env
        environment:
            - SERVER_CONFIG_FOLDER=/components
            - MANIFEST_FOLDER=/manifests
        volumes:
            - ./components:/components:ro
            - ./manifests:/manifests
            - simulation_logs:/logs

volumes:
    simulation_logs:
        external: true
        name: simulation_logs
