Simulation:
    Name: "Test simulation with platform manager."
    Description: "This is a description text for this simulation."
    InitialStartTime: "2020-10-01T00:00:00.000Z"
    EpochLength: 3600
    MaxEpochCount: 24

Components:
    StaticTimeSeriesResource:
        load_1:
            ResourceType: Load
            ResourceStateFile: /resources/load_1.csv
        load_2:
            ResourceType: Load
            ResourceStateFile: /resources/load_2.csv
        generator:
            duplication_count: 2
            ResourceType: Generator
            ResourceStateFile: /resources/generator.csv

    Dummy:
        slow_dummy: {}
        fast_dummy:
            duplication_count: 2
            MinSleepTime: 0.5
            MaxSleepTime: 1.5
