simulation:
    name: "Energy community demo"
    description: "This scenario describes the behavior of a small rural energy community of four detached houses. The houses have no controllable loads or storages but two of them have a small scale PV systems installed and one has a electric vehicle charging. Scenario spans over one day with hourly resolution (epochs)."
    start_time: "2020-06-25T00:00:00.000+03:00"
    epoch_length: 3600
    max_epochs: 24

components:  # these are the names of the component implementations
    # the component implementations that are currently supported:
    # - static components: Grid
    # - dynamic components: StaticTimeSeriesResource, Dummy

    # duplication_count is reserved keyword and cannot be used as a parameter for a component instance

    StaticTimeSeriesResource:
        load_1:                   # The name of this StaticTimeSeriesResource instance in the simulation run
            RESOURCE_TYPE: Load   # RESOURCE_TYPE environment variable for the dynamic component
            RESOURCE_STATE_CSV_FILE: /resources/Load1.csv
        load_2:
            RESOURCE_TYPE: Load
            RESOURCE_STATE_CSV_FILE: /resources/Load2.csv
        load_3:
            RESOURCE_TYPE: Load
            RESOURCE_STATE_CSV_FILE: /resources/Load3.csv
        load_4:
            RESOURCE_TYPE: Load
            RESOURCE_STATE_CSV_FILE: /resources/Load4.csv
        electric_vehicle:
            RESOURCE_TYPE: Load
            RESOURCE_STATE_CSV_FILE: /resources/EV.csv
        pv_small:
            RESOURCE_TYPE: Generator
            RESOURCE_STATE_CSV_FILE: /resources/PV_small.csv
        pv_large:
            RESOURCE_TYPE: Generator
            RESOURCE_STATE_CSV_FILE: /resources/PV_large.csv

    Dummy:
        dummy:
            duplication_count: 2  # Create 2 components, named dummy_1 and dummy_2, with otherwise identical parameters
            MIN_SLEEP_TIME: 2     # MIN_SLEEP_TIME Environment variable for the dynamic component
            MAX_SLEEP_TIME: 2
