simulation:
    name: "Energy community demo"
    description: "This scenario describes the behavior of a small rural energy community of four detached houses. The houses have no controllable loads or storages but two of them have a small scale PV systems installed and one has a electric vehicle charging. Scenario spans over one day with hourly resolution (epochs)."
    start_time: "2020-06-25T00:00:00.000+03:00"
    epoch_length: 3600
    max_epochs: 24

    # the Docker images for the simulation manager and the log writer
    manager_image: simulation_manager:0.4
    logwriter_image: log_writer:0.2

processes:
    load_1:
        image: static-time-series-resource:0.1
        environment:
            RESOURCE_TYPE: Load
            RESOURCE_STATE_CSV_FILE: /resources/Load1.csv

    load_2:
        image: static-time-series-resource:0.1
        environment:
            RESOURCE_TYPE: Load
            RESOURCE_STATE_CSV_FILE: /resources/Load2.csv

    load_3:
        image: static-time-series-resource:0.1
        environment:
            RESOURCE_TYPE: Load
            RESOURCE_STATE_CSV_FILE: /resources/Load3.csv

    load_4:
        image: static-time-series-resource:0.1
        environment:
            RESOURCE_TYPE: Load
            RESOURCE_STATE_CSV_FILE: /resources/Load4.csv

    electric_vehicle:
        image: static-time-series-resource:0.1
        environment:
            RESOURCE_TYPE: Load
            RESOURCE_STATE_CSV_FILE: /resources/EV.csv

    pv_small:
        image: static-time-series-resource:0.1
        environment:
            RESOURCE_TYPE: Generator
            RESOURCE_STATE_CSV_FILE: /resources/PV_small.csv

    pv_large:
        image: static-time-series-resource:0.1
        environment:
            RESOURCE_TYPE: Generator
            RESOURCE_STATE_CSV_FILE: /resources/PV_large.csv

    dummy:
        image: dummy:0.4
        count: 1
        environment:
            MIN_SLEEP_TIME: 2
            MAX_SLEEP_TIME: 2
