simulation:
    name: "Test simulation with platform manager."
    description: "This is a description text for this simulation."
    start_time: "2020-10-01T00:00:00.000Z"
    epoch_length: 3600
    max_epochs: 24

    # the Docker images for the simulation manager and the log writer
    manager_image: simulation_manager:0.3
    logwriter_image: log_writer:0.1

processes:
    default_dummy:
        image: dummy:0.3

    fast_dummy:
        image: dummy:0.3
        count: 3
        environment:
            MIN_SLEEP_TIME: 0.1
            MAX_SLEEP_TIME: 0.5

    slow_dummy:
        image: dummy:0.3
        count: 2
        environment:
            MIN_SLEEP_TIME: 5
            MAX_SLEEP_TIME: 10
