version: '3.5'

services:

    rabbitmq:
        image: rabbitmq:3.8.4-management
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        env_file:
            - env/rabbitmq.env
        networks:
            - rabbitmq_network

    mongodb:
        image: mongo:4.2.7
        container_name: mongodb
        restart: always
        expose:
            - 27017
        env_file:
            - env/mongodb.env
        volumes:
            - mongodb_data:/data/db
        networks:
            - mongodb_network

    mongo_express:
        image: mongo-express:0.54.0
        container_name: mongo_express
        restart: always
        depends_on:
            - mongodb
        env_file:
            - env/mongo_express.env
        ports:
            - 8181:8081
        networks:
            - mongodb_network

    log_reader:
        image: log_reader:0.4
        container_name: log_reader
        restart: always
        depends_on:
            - mongodb
        env_file:
            - env/components_mongodb.env
        environment:
            - MONGODB_APPNAME=log_writer
        ports:
            - 8180:8080
        networks:
            - mongodb_network

    log_writer_management:
        image: log_writer:0.2
        container_name: log_writer_management
        restart: always
        depends_on:
            - mongodb
        env_file:
            - env/components_mongodb.env
            - env/components_logwriter.env
        volumes:
            - simulation_logs
        networks:
            - mongodb_network
            - rabbitmq_network
volumes:
    mongodb_data:
        external: true
        name: mongodb_data
    simulation_logs:
        external: true
        name: simulation_logs

networks:
    rabbitmq_network:
        external: true
        name: rabbitmq_network
    mongodb_network:
        external: true
        name: mongodb_network
